export const ActionTypes =  {
  SET_PRODUCTS : "SET_PRODUCTS",
  SELECTED_PRODUCT : "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
  SET_CARTS  : "SET_CARTS",
  INSCREASE_CART : "INSCREASE_CART",
  DESCREASE_CART : "DESCREASE_CART",
  REMOVE_CART : "REMOVE_CART",
  SELECTED_CART : 'SELECTED_CART',
}